In [147]:
import pandas as pd

data_url = "https://github.com/jkramorenko/homework_trades/blob/main/data.xls?raw=True"
requests = pd.read_excel(data_url, sheet_name="Заявки клиентов")
trades = pd.read_excel(data_url, sheet_name="Сделки клиентов")
all_market = pd.read_excel(data_url, sheet_name="Сделки всего рынка")

pd.options.display.float_format = '{:,.8f}'.format
pd.options.display.max_rows = 100
pd.options.display.min_rows = 100

In [148]:
# <1.1 Объем сделок рынка по инструменту>
all_market.groupby(['Инструмент','Дата']).aggregate({'Объем':'sum'})

                          Объем
Инструмент   Дата
0fRm7NyUxEdG 20180415        17
             20180418        20
1Dbr3T9Wpl3x 20180413        50
             20180418         3
6OBf0mwp3jLi 20180414      2733
             20180418        10
7srkc        20180411     40000
             20180413     10000
             20180414    280000
             20180415    350000
             20180418    730000
ETN9hjIEdlDW 20180413       124
             20180414    314261
             20180415    920315
             20180418    801829
             20180717       153
F9Tw         20180411        88
             20180413       637
             20180414     10224
             20180415      4969
             20180418      2195
             20180717       151
GjgR         20180411     90000
             20180413   2290000
             20180414   7120000
             20180415  10220000
             20180418   6140000
             20180717     50000
Jnfh         20180413      2200
             20180414    117000
             20180415    149800
             20180418   6442900
             20180717       400
Kr1d         20180411      4202
             20180413      3798
             20180414     84365
             20180415     67296
             20180418     60935
             20180717      1611
N0ea         20180411    620000
             20180413   5030000
             20180414  27560000
             20180415  19820000
             20180418  47440000
             20180717    170000
R8pBIopqatlp 20180413         3
             20180414        49
             20180415       125
             20180418        38
UQEm31sDqlAg 20180414      4526
             20180415       409
             20180418       112
             20180717         6
aCiw         20180413        70
             20180414      8923
             20180415      4593
             20180418     21762
             20180717         2
gAfLE34byRcu 20180411       236
             20180413      5066
             20180414     49928
             20180415     24853
             20180418     20619
iCtXYnx8Ub8b 20180413         5
             20180414       505
             20180415       674
             20180418       216
jq1v         20180411   3974100
             20180413   7562500
             20180414  36376000
             20180415  38045700
             20180418  30608900
             20180717    502000
jvNC         20180414       170
             20180415       200
             20180717        10
momz         20180411       280
             20180413      1210
             20180414      5490
             20180415      1090
             20180418      7060
             20180717        70
t4yJZ        20180413      3000
             20180414     38000
             20180415    495000
             20180418    160000
znKu         20180411      9400
             20180413     46100
             20180414   1006400
             20180415   2901200
             20180418    159400

In [149]:
# <1.2 Объем сделок клиентов по инструменту>
trades.groupby(['Инструмент','Дата']).aggregate({'Объем':'sum'})

                          Объем
Инструмент   Дата
0fRm7NyUxEdG 20180413         6
             20180415        18
             20180418        29
             20180428       541
             20180717         5
1Dbr3T9Wpl3x 20180411        16
             20180413       324
             20180418         5
6OBf0mwp3jLi 20180418        10
             20180428      3178
7srkc        20180411   1370000
             20180412    110000
             20180413     80000
             20180415    110000
             20180418    610000
             20180428    200000
             20180717   1400000
ETN9hjIEdlDW 20180411      1244
             20180412      4208
             20180413     16711
             20180415      5430
             20180418      2185
             20180428      2530
             20180717     17176
F9Tw         20180411      4390
             20180412      7818
             20180413      3364
             20180415      4264
             20180418      4034
             20180428      3492
             20180717      6549
GjgR         20180411   2260000
             20180412   2740000
             20180413   4540000
             20180415   3940000
             20180418   4680000
             20180428    510000
             20180717    570000
Jnfh         20180411      3300
             20180412      6200
             20180413    102300
             20180415     50700
             20180418   4075800
             20180428     68800
             20180717     21000
Kr1d         20180411     71166
             20180412     98610
             20180413    245650
             20180415     68394
             20180418     81652
...                         ...
aCiw         20180418      8022
             20180428       480
             20180717       113
gAfLE34byRcu 20180411     15802
             20180412      5824
             20180413      4507
             20180415      7530
             20180418     31777
             20180428     10100
iCtXYnx8Ub8b 20180411         3
             20180412       215
             20180413       165
             20180415       416
             20180418         8
             20180428        88
jq1v         20180411   9313900
             20180412  14790200
             20180413  16577200
             20180415   8578600
             20180418  15564400
             20180428   5468000
             20180717   2920700
jvNC         20180411        10
             20180412        70
             20180413        10
             20180415        20
             20180418       240
             20180428     10390
             20180717       280
momz         20180411      4520
             20180412      7790
             20180413      4040
             20180415       760
             20180418     11960
             20180428     22250
             20180717       780
t4yJZ        20180411     10000
             20180412     31000
             20180413     54000
             20180415    317000
             20180418     92000
             20180428     11000
             20180717      7000
zigDotC2R7Oe 20180428      4043
znKu         20180411    154800
             20180412    306600
             20180413    250400
             20180415    945000
             20180418    148900
             20180428    250700

[127 rows x 1 columns]

In [150]:
# <1.3 Средневзвешенная цена по инструменту>
all_market.groupby(['Инструмент','Дата']).apply(lambda group: group['Сумма'].sum() / group['Объем'].sum())

Инструмент    Дата
0fRm7NyUxEdG  20180415     909.97647059
              20180418     944.48500000
1Dbr3T9Wpl3x  20180413   1,377.21500000
              20180418   1,539.00000000
6OBf0mwp3jLi  20180414   1,109.79136480
              20180418   1,109.00000000
7srkc         20180411       0.33925000
              20180413       0.34850000
              20180414       0.33198214
              20180415       0.33517143
              20180418       0.34897260
ETN9hjIEdlDW  20180413   1,070.38403226
              20180414   1,066.50446050
              20180415   1,067.96434673
              20180418   1,069.25715367
              20180717   1,049.75960784
F9Tw          20180411   1,170.90227273
              20180413   1,168.13171115
              20180414   1,166.64731025
              20180415   1,167.69851077
              20180418   1,168.19302961
              20180717   1,186.86953642
GjgR          20180411       0.29350000
              20180413       0.28227074
              20180414       0.27816362
              20180415       0.28384295
              20180418       0.28868730
              20180717       0.32900000
Jnfh          20180413       6.74000000
              20180414       6.56954701
              20180415       6.61198264
              20180418       8.77340266
              20180717       7.00000000
Kr1d          20180411     100.11471918
              20180413     102.24859136
              20180414     100.80863806
              20180415     101.02840362
              20180418     101.95862230
              20180717     109.19174426
N0ea          20180411       0.05133790
              20180413       0.05371402
              20180414       0.05259144
              20180415       0.05228688
              20180418       0.05055398
              20180717       0.04989118
R8pBIopqatlp  20180413   1,545.08000000
              20180414   1,548.86020408
              20180415   1,548.50232000
              20180418   1,546.98263158
UQEm31sDqlAg  20180414   1,181.02061423
              20180415   1,184.96283619
              20180418   1,179.08035714
              20180717   1,182.41666667
aCiw          20180413   1,969.14285714
              20180414   2,289.22391572
              20180415   2,576.60570433
              20180418   3,386.64208253
              20180717   2,505.00000000
gAfLE34byRcu  20180411     907.16144068
              20180413     941.66960126
              20180414     878.20635315
              20180415     852.82971472
              20180418     781.14230564
iCtXYnx8Ub8b  20180413   1,092.16000000
              20180414   1,045.22831683
              20180415   1,051.16943620
              20180418   1,036.47592593
jq1v          20180411      40.27512732
              20180413      40.07647934
              20180414      39.67254794
              20180415      40.19973749
              20180418      41.01645904
              20180717      35.25576394
jvNC          20180414     141.20588235
              20180415     139.82500000
              20180717     139.00000000
momz          20180411      74.76071429
              20180413      71.91652893
              20180414      71.16612022
              20180415      71.26513761
              20180418      73.44178470
              20180717      74.97142857
t4yJZ         20180413       7.01500000
              20180414       6.94842105
              20180415       7.15902020
              20180418       6.62978125
znKu          20180411       1.53104255
              20180413       1.54110846
              20180414       1.54530574
              20180415       1.58819016
              20180418       1.56841970
dtype: float64

In [151]:
# <1.4 Количество заявок клиентов по инструменту>
requests.groupby(['Инструмент','Дата']).aggregate({'Объем':'count'})

                       Объем
Инструмент   Дата
0fRm7NyUxEdG 20180411      4
             20180412     12
             20180413     16
             20180415     27
             20180418     46
             20180428     69
             20180717     13
1Dbr3T9Wpl3x 20180412     10
             20180413     16
             20180415      6
             20180418      7
             20180428     10
6OBf0mwp3jLi 20180418      2
             20180428      1
             20180717      2
7srkc        20180411      7
             20180412     50
             20180413     38
             20180415     43
             20180418     77
             20180428     54
             20180717     57
ETN9hjIEdlDW 20180411     13
             20180412     37
             20180413    101
             20180415     51
             20180418     63
             20180428     68
             20180717    243
F9Tw         20180411      5
             20180412    330
             20180413    555
             20180415    527
             20180418    441
             20180428    509
             20180717    542
GjgR         20180411     18
             20180412    148
             20180413    278
             20180415    260
             20180418    249
             20180428     64
             20180717     43
Jnfh         20180411     25
             20180412     77
             20180413    149
             20180415    118
             20180418   1549
             20180428    216
             20180717     73
...                      ...
aCiw         20180418   1055
             20180428    203
             20180717     31
gAfLE34byRcu 20180411     39
             20180412    295
             20180413    230
             20180415    736
             20180418   2322
             20180428    793
iCtXYnx8Ub8b 20180411      1
             20180412     34
             20180413     46
             20180415     22
             20180418     17
             20180428     34
             20180717     14
jq1v         20180411    290
             20180412   3643
             20180413   5131
             20180415   3289
             20180418   5773
             20180428   4239
             20180717   1642
jvNC         20180411      8
             20180412     26
             20180413     26
             20180415     24
             20180418     39
             20180428    351
             20180717     72
momz         20180411     24
             20180412    193
             20180413    152
             20180415    108
             20180418    205
             20180428    419
             20180717     77
t4yJZ        20180411     10
             20180412     58
             20180413     56
             20180415     92
             20180418     92
             20180428     30
             20180717     39
zigDotC2R7Oe 20180428    250
znKu         20180412    183
             20180413    167
             20180415    259
             20180418    123
             20180428    124

[132 rows x 1 columns]

In [152]:
# <1.5 Количество снятых заявок клиента по инструменту>
requests.loc[requests['Объем'] == requests['Остаток объема']].groupby(['Инструмент','Дата']).aggregate({'Объем':'count'})

                       Объем
Инструмент   Дата
0fRm7NyUxEdG 20180411      4
             20180412     12
             20180413     14
             20180415     21
             20180418     33
             20180428     37
             20180717     12
1Dbr3T9Wpl3x 20180412     10
             20180413      9
             20180415      6
             20180418      5
             20180428     10
6OBf0mwp3jLi 20180418      1
             20180717      2
7srkc        20180411      5
             20180412     46
             20180413     30
             20180415     37
             20180418     56
             20180428     49
             20180717     42
ETN9hjIEdlDW 20180411     13
             20180412     23
             20180413     69
             20180415     24
             20180418     35
             20180428     40
             20180717    102
F9Tw         20180411      4
             20180412    100
             20180413    225
             20180415    232
             20180418    153
             20180428    203
             20180717    163
GjgR         20180411     18
             20180412     70
             20180413    126
             20180415    110
             20180418    108
             20180428     48
             20180717     26
Jnfh         20180411     25
             20180412     61
             20180413     88
             20180415     71
             20180418    484
             20180428    130
             20180717     56
Kr1d         20180411      3
...                      ...
aCiw         20180418    360
             20180428    120
             20180717     24
gAfLE34byRcu 20180411     34
             20180412    144
             20180413    130
             20180415    394
             20180418   1226
             20180428    453
iCtXYnx8Ub8b 20180411      1
             20180412     26
             20180413     24
             20180415     12
             20180418     14
             20180428     21
             20180717     14
jq1v         20180411    213
             20180412   1590
             20180413   2297
             20180415   1755
             20180418   2571
             20180428   2166
             20180717    970
jvNC         20180411      8
             20180412     22
             20180413     25
             20180415     23
             20180418     23
             20180428    138
             20180717     62
momz         20180411     14
             20180412    105
             20180413    100
             20180415     85
             20180418     97
             20180428    202
             20180717     57
t4yJZ        20180411      9
             20180412     43
             20180413     37
             20180415     52
             20180418     52
             20180428     26
             20180717     34
zigDotC2R7Oe 20180428    135
znKu         20180412    101
             20180413     95
             20180415    101
             20180418     67
             20180428     64

[131 rows x 1 columns]

In [153]:
# <1.6 Количество сделок клиента с контрагентом>
res = trades.groupby(['Инструмент','Дата']).aggregate({'Клиент-констрагент':'count'})
res[res['Клиент-констрагент']>0]

                       Клиент-констрагент
Инструмент   Дата
0fRm7NyUxEdG 20180415                   2
             20180418                   4
             20180428                  21
1Dbr3T9Wpl3x 20180413                   4
             20180418                   1
7srkc        20180411                   8
             20180413                   1
             20180418                   5
             20180428                   1
             20180717                   4
ETN9hjIEdlDW 20180411                   4
             20180413                  10
             20180415                   3
             20180418                   5
             20180428                   5
             20180717                   9
F9Tw         20180411                 131
             20180412                 141
             20180413                 157
             20180415                 146
             20180418                 122
             20180428                 102
             20180717                 250
GjgR         20180411                  22
             20180412                  10
             20180413                  24
             20180415                  25
             20180418                  19
             20180428                   1
             20180717                   2
Jnfh         20180412                   4
             20180413                  10
             20180415                   7
             20180418                 119
             20180428                   5
             20180717                   6
Kr1d         20180411                 191
             20180412                 341
             20180413                 338
             20180415                 232
             20180418                 300
             20180428                 126
             20180717                 366
N0ea         20180411                  22
             20180412                  17
             20180413                  10
             20180415                   4
             20180418                  12
             20180428                 130
             20180717                   3
...                                   ...
R8pBIopqatlp 20180413                   1
             20180415                   5
             20180418                   5
             20180428                  15
UQEm31sDqlAg 20180428                  24
             20180717                   1
aCiw         20180412                   1
             20180413                  33
             20180415                  42
             20180418                  81
             20180428                  10
gAfLE34byRcu 20180411                  52
             20180412                  32
             20180413                   4
             20180415                  45
             20180418                 148
             20180428                  50
iCtXYnx8Ub8b 20180413                   8
             20180415                   1
             20180428                   8
jq1v         20180411                 130
             20180412                 214
             20180413                 303
             20180415                 115
             20180418                 252
             20180428                  56
             20180717                  26
jvNC         20180412                   2
             20180418                   1
             20180428                  32
momz         20180411                  25
             20180412                  22
             20180413                  16
             20180415                   7
             20180418                  25
             20180428                  82
             20180717                   1
t4yJZ        20180411                   1
             20180412                   1
             20180413                   1
             20180415                  14
             20180418                   8
             20180717                   2
zigDotC2R7Oe 20180428                  34
znKu         20180411                   2
             20180412                   5
             20180413                   4
             20180415                  16
             20180418                   4
             20180428                  12

[102 rows x 1 columns]

In [154]:
# <2.1 Доля клиентов в объеме рынка>

total_sum = trades['Сумма'].sum()

trades.groupby(['Клиент']).apply(lambda group: 100 * group['Сумма'].sum() / total_sum)

Клиент
00OqMJEz5q   0.00001237
00uuaSqarP   0.00043155
011CViGkF1   0.00020830
023zVtAPLu   0.02646668
02ESyPJdYy   0.00058517
034vjcGUgY   0.00000665
04OUzjBnkx   0.01349646
04py0PdHKJ   0.00004349
04zXvrsfym   0.00125612
05ibLTUMuU   0.00008631
06Bek9UFos   0.00010558
06UpujRfdl   0.00001236
07KY3mUUzx   0.00519518
07SLkXH0i6   0.00006683
07XadhbP1q   0.00059145
09KgWScae5   0.00023209
0AKg971Hgb   0.00016736
0AalbKL5kI   0.00321321
0AnMl4qW4y   0.00121549
0BIryf50n3   0.00673959
0C32UBr3no   0.00314881
0C67jurIHm   0.00362404
0CWvtJuBv8   0.00754018
0DaAW1aAri   0.00012175
0DgRwDPclA   0.00000312
0EplVzrhfI   0.00046954
0FBUMggiev   0.03058732
0FCg3RIF4p   0.00034996
0FkJXcWO3q   0.14387238
0GauSmmMBi   0.00245202
0Gfq0bl9mX   0.00003579
0GzzbCpZfP   0.00018390
0HbcEJkDYj   0.00016728
0IRtx7KdVc   0.00005164
0J8AD13eox   0.00003569
0JjLvRINZU   0.00004523
0JutG8TBuv   0.00196094
0KUHViMNYY   0.09025727
0KjFGKh9Oe   0.00030315
0KoQrFExoZ   0.00118519
0L2rPvrUOu   0.00000301
0LiLvggbeO   0.00015493
0LyKcoJc6h   0.00038093
0MoGQKtslu   0.01237198
0MoWotcMeq   0.00122737
0NRQ61wexi   0.00021431
0NczEDBQsW   0.00607228
0OSJ5YqxMj   0.00009477
0OrvtSvuk4   0.00238868
0PgnFpuaie   0.00058229
                ...
zkPFAMQjyr   0.00053941
zkw3h5AzZg   0.00028933
zlMwhBeulc   0.00010869
zlhtcHGgvp   0.00072402
zlqIOGtbqs   0.00030925
zmvJiXCrL6   0.00003388
zmyTrplobg   0.00000667
znQ5xIjhc3   0.00012443
znr1oIc6Ot   0.00004000
zoDtxpY70l   0.00007183
zoEEt5gyzr   0.00000312
zoLhdmkChz   0.46387031
zox6YGJpjI   0.00015478
zpCAaSB3ni   0.00004630
zpjwqxcuU1   0.00037354
zqB8CcZWgi   0.00007240
zrIhp4zx6h   0.00076618
zraeNMjRxP   0.00270048
zs5xdOQqXe   0.00012300
zsDrKwOaxz   0.00010757
zsOamgn93F   0.01820000
zsheuu0mh4   0.00306502
zsyso1jHHo   0.00007814
ztIwAf8uap   0.00011690
ztYzmFJskR   0.02144188
ztfmXT3NnF   0.00130311
ztl2FINybL   0.00392727
ztuWU8Pa5f   0.00000302
zuE9p6qZ6X   0.00012239
zuQELy3m3R   0.00007740
zuidLpuklU   0.00014313
zvG5SCtdXT   0.00003100
zvqSx0iaXa   0.00024218
zwnAdxJlug   0.00006145
zwu621JqvL   0.00003025
zwuDoWBuMF   0.00001238
zwwoNbp5Kk   0.00000335
zxDnlKcY2i   0.00027818
zxFEq2Xeyf   0.00060820
zxVbWqDpRM   0.00048870
zxjKlnt1DX   0.00062655
zyfquvbqOH   0.00377440
zyiBzAdfqi   0.01229058
zymeHXlTwk   0.00003992
zz60nxW6bf   0.00021470
zzEczuTl1p   0.00020891
zzOY2QnbBJ   0.00056643
zzVBu6xVNs   0.00000306
zzcWEayzxa   0.00035216
zzevNIdbOO   0.00085444
Length: 8554, dtype: float64

In [155]:
# <2.2 Сделки, цена которых отклоняется от средневзвешенной более чем на 1, 2 или 5% (выбрать порог самостоятельно по количеству сигналов)>
wavg = all_market.groupby(['Инструмент']).apply(lambda group: group['Сумма'].sum() / group['Объем'].sum())

def filter_avg(row):
    avg_value = wavg[row['Инструмент']]
    return (100 * abs(row['Цена'] - avg_value)/avg_value) > 5

all_market[all_market.apply(filter_avg, axis=1)]

,Номер сделки,Дата,Время,Инструмент,Цена,Объем,Сумма,Покупка/Продажа
4,3133835856,20180414,151201,gAfLE34byRcu,84.99000000,2,"1,699.80000000",B
6,3133838040,20180414,151249,gAfLE34byRcu,84.00000000,10,"8,400.00000000",S
107,3132499520,20180413,162123,Jnfh,6.76000000,1000,"6,760.00000000",B
124,3132446787,20180413,160036,gAfLE34byRcu,94.99000000,110,"104,489.00000000",B
125,3132446788,20180413,160036,gAfLE34byRcu,94.99000000,20,"18,998.00000000",B
133,3132632707,20180414,81000,gAfLE34byRcu,94.92000000,6,"5,695.20000000",B
134,3132632719,20180414,81000,aCiw,"2,285.00000000",1,"2,285.00000000",S
135,3132633432,20180414,81006,aCiw,"2,260.00000000",1,"2,260.00000000",S
136,3132633583,20180414,81007,aCiw,"2,280.00000000",1,"2,280.00000000",S
141,3132631588,20180414,80952,aCiw,"2,280.00000000",5,"11,400.00000000",B
143,3132642155,20180414,81104,ETN9hjIEdlDW,106.99600000,1,"1,069.96000000",B
144,3132642173,20180414,81104,ETN9hjIEdlDW,106.99800000,2,"2,139.96000000",B
146,3132646824,20180414,81144,aCiw,"2,195.00000000",21,"46,095.00000000",S
147,3132647148,20180414,81147,aCiw,"2,180.00000000",51,"111,180.00000000",S
148,3132647307,20180414,81148,aCiw,"2,180.00000000",2,"4,360.00000000",S
150,3132631251,20180414,80949,aCiw,"2,240.00000000",1,"2,240.00000000",S
153,3132636414,20180414,81020,aCiw,"2,235.00000000",4,"8,940.00000000",S
154,3132637273,20180414,81024,aCiw,"2,200.00000000",1,"2,200.00000000",S
156,3132625387,20180414,80909,aCiw,"2,345.00000000",5,"11,725.00000000",B
157,3132625388,20180414,80909,aCiw,"2,350.00000000",1,"2,350.00000000",B
158,3132626647,20180414,80915,aCiw,"2,335.00000000",1,"2,335.00000000",S
159,3132626685,20180414,80915,aCiw,"2,320.00000000",1,"2,320.00000000",S
160,3132627350,20180414,80918,aCiw,"2,295.00000000",1,"2,295.00000000",S
168,3132620514,20180414,80855,aCiw,"2,380.00000000",1,"2,380.00000000",S
170,3132621350,20180414,80857,aCiw,"2,495.00000000",1,"2,495.00000000",S
172,3132616100,20180414,80825,aCiw,"2,180.00000000",1,"2,180.00000000",S
176,3132649615,20180414,81206,aCiw,"2,070.00000000",8,"16,560.00000000",B
179,3132669407,20180414,81450,aCiw,"2,130.00000000",1,"2,130.00000000",S
189,3132667689,20180414,81433,aCiw,"2,130.00000000",1,"2,130.00000000",B
190,3132668262,20180414,81438,aCiw,"2,135.00000000",3,"6,405.00000000",B
191,3132650598,20180414,81216,aCiw,"2,000.00000000",4,"8,000.00000000",S
192,3132651610,20180414,81225,aCiw,"2,035.00000000",1,"2,035.00000000",S
193,3132652877,20180414,81240,aCiw,"2,095.00000000",3,"6,285.00000000",B
198,3132648959,20180414,81159,aCiw,"2,075.00000000",1,"2,075.00000000",S
202,3132640996,20180414,81053,aCiw,"2,205.00000000",1,"2,205.00000000",S
203,3132658125,20180414,81321,aCiw,"2,175.00000000",9,"19,575.00000000",B
204,3132658843,20180414,81327,aCiw,"2,210.00000000",24,"53,040.00000000",B
210,3132694259,20180414,81811,ETN9hjIEdlDW,106.64700000,1,"1,066.47000000",B
212,3132695371,20180414,81824,aCiw,"2,425.00000000",1,"2,425.00000000",S
213,3132695734,20180414,81828,aCiw,"2,430.00000000",1,"2,430.00000000",B
214,3132695893,20180414,81829,aCiw,"2,430.00000000",5,"12,150.00000000",S
215,3132696067,20180414,81831,aCiw,"2,470.00000000",50,"123,500.00000000",B
217,3132699090,20180414,81859,aCiw,"2,445.00000000",2,"4,890.00000000",S
218,3132699096,20180414,81859,aCiw,"2,430.00000000",2,"4,860.00000000",S
219,3132699145,20180414,81900,aCiw,"2,490.00000000",4,"9,960.00000000",B
221,3132699794,20180414,81905,aCiw,"2,470.00000000",1,"2,470.00000000",B
223,3132691550,20180414,81744,aCiw,"2,335.00000000",1,"2,335.00000000",B
224,3132692119,20180414,81750,aCiw,"2,360.00000000",3,"7,080.00000000",B
225,3132692278,20180414,81752,aCiw,"2,400.00000000",1,"2,400.00000000",B
226,3132692289,20180414,81752,aCiw,"2,400.00000000",3,"7,200.00000000",B
...,...,...,...,...,...,...,...,...
64480,3136169216,20180418,121642,aCiw,"3,300.00000000",1,"3,300.00000000",B
64481,3136169224,20180418,121642,aCiw,"3,300.00000000",1,"3,300.00000000",B
64482,3136169225,20180418,121642,aCiw,"3,300.00000000",1,"3,300.00000000",B
64504,3136064731,20180418,113357,gAfLE34byRcu,73.55000000,3,"2,206.50000000",S
64505,3136064732,20180418,113357,gAfLE34byRcu,73.54000000,1,735.40000000,S
64506,3136064733,20180418,113357,gAfLE34byRcu,73.47000000,4,"2,938.80000000",S
64507,3136064734,20180418,113357,gAfLE34byRcu,73.46000000,92,"67,583.20000000",S
64508,3136064758,20180418,113358,gAfLE34byRcu,73.46000000,8,"5,876.80000000",S
64509,3136065825,20180418,113431,gAfLE34byRcu,73.46000000,79,"58,033.40000000",B
64682,3136055503,20180418,112802,gAfLE34byRcu,73.59000000,1,735.90000000,B
64707,3136066437,20180418,113452,gAfLE34byRcu,73.46000000,20,"14,692.00000000",S
64708,3136066438,20180418,113452,gAfLE34byRcu,73.42000000,1,734.20000000,S
64709,3136066439,20180418,113452,gAfLE34byRcu,73.41000000,1,734.10000000,S
64710,3136066440,20180418,113452,gAfLE34byRcu,73.41000000,2,"1,468.20000000",S
64711,3136066441,20180418,113452,gAfLE34byRcu,73.40000000,1,734.00000000,S
64712,3136066442,20180418,113452,gAfLE34byRcu,73.40000000,1,734.00000000,S
64828,3136084587,20180418,114246,iCtXYnx8Ub8b,105.98000000,2,"2,119.60000000",B
64858,3136059559,20180418,113026,gAfLE34byRcu,73.80000000,9,"6,642.00000000",B
64921,3136070777,20180418,113708,gAfLE34byRcu,73.36000000,2,"1,467.20000000",S
64922,3136070778,20180418,113708,gAfLE34byRcu,73.36000000,1,733.60000000,S
64923,3136070779,20180418,113708,gAfLE34byRcu,73.35000000,4,"2,934.00000000",S
64924,3136070780,20180418,113708,gAfLE34byRcu,73.35000000,1,733.50000000,S
64925,3136070781,20180418,113708,gAfLE34byRcu,73.30000000,1,733.00000000,S
64926,3136070782,20180418,113708,gAfLE34byRcu,73.30000000,1,733.00000000,S
64927,3136070783,20180418,113708,gAfLE34byRcu,73.24000000,83,"60,789.20000000",S
64938,3136067015,20180418,113513,gAfLE34byRcu,73.40000000,8,"5,872.00000000",S
64939,3136067016,20180418,113513,gAfLE34byRcu,73.39000000,5,"3,669.50000000",S
64940,3136067017,20180418,113513,gAfLE34byRcu,73.38000000,1,733.80000000,S
64941,3136067018,20180418,113513,gAfLE34byRcu,73.38000000,1,733.80000000,S
64942,3136067019,20180418,113513,gAfLE34byRcu,73.37000000,2,"1,467.40000000",S
64943,3136067020,20180418,113513,gAfLE34byRcu,73.37000000,1,733.70000000,S
64944,3136067021,20180418,113513,gAfLE34byRcu,73.37000000,10,"7,337.00000000",S
64975,3136071585,20180418,113726,aCiw,"3,205.00000000",1,"3,205.00000000",B
64976,3136071586,20180418,113726,aCiw,"3,205.00000000",1,"3,205.00000000",B
65011,3136052861,20180418,112604,gAfLE34byRcu,73.86000000,4,"2,954.40000000",B
65088,3136070925,20180418,113712,gAfLE34byRcu,73.24000000,17,"12,450.80000000",S
65089,3136070926,20180418,113712,gAfLE34byRcu,73.23000000,5,"3,661.50000000",S
65090,3136070927,20180418,113712,gAfLE34byRcu,73.23000000,1,732.30000000,S
65091,3136070928,20180418,113712,gAfLE34byRcu,73.22000000,2,"1,464.40000000",S
65092,3136070929,20180418,113712,gAfLE34byRcu,73.22000000,1,732.20000000,S
65093,3136070930,20180418,113712,gAfLE34byRcu,73.21000000,4,"2,928.40000000",S
65210,3136080147,20180418,114049,aCiw,"3,230.00000000",10,"32,300.00000000",B
65212,3136082683,20180418,114155,ETN9hjIEdlDW,106.95100000,2,"2,139.02000000",S
65244,3136055563,20180418,112804,aCiw,"3,195.00000000",1,"3,195.00000000",B
65256,3136072016,20180418,113739,aCiw,"3,210.00000000",1,"3,210.00000000",B
65257,3136072017,20180418,113739,aCiw,"3,215.00000000",2,"6,430.00000000",B
65258,3136072018,20180418,113739,aCiw,"3,215.00000000",1,"3,215.00000000",B
65260,3136072030,20180418,113740,aCiw,"3,220.00000000",5,"16,100.00000000",B
65272,3136066915,20180418,113510,gAfLE34byRcu,73.62000000,8,"5,889.60000000",B
65328,3136077915,20180418,113945,aCiw,"3,230.00000000",1,"3,230.00000000",B

In [156]:
# <2.4 Максимальное количество единовременно снятых клиентом заявок>
requests[['Клиент','Время снятия заявки', 'Номер заявки']].rename(columns={'Номер заявки':'Count'}).groupby(['Клиент','Время снятия заявки']).count().sort_values(by='Count').groupby(level=0).tail(1)

                                Count
Клиент     Время снятия заявки
gjTzknzWOq 122049                   1
gjm9youU8K 121756                   1
gk06MW9FQ7 120428                   1
gjKzV7ukSp 81132                    1
gkkwXCAMN8 152515                   1
gl4mLQZRT1 165358                   1
glW7PtQEwj 164855                   1
gl3PSIpi3e 84539                    1
gisqctWOh0 165704                   1
giYPGhwPOT 154410                   1
ggbyA7cOPZ 131436                   1
ggkE8RaW5b 165402                   1
gh5wZkWYgj 165410                   1
ghEkmINpnn 164412                   1
gik3vbWrpr 151522                   1
ghGItW1wC3 165402                   1
ghzGzAR3Kc 95219                    1
giQUSMa3Ab 140345                   1
giVAJSRI9p 133329                   1
ghmlbCbV5c 104503                   1
glovefHlhc 124855                   1
goir0Vj4fl 165407                   1
gok5qrOrMJ 92431                    1
goty2LoZDd 102931                   1
gpinxm2H1k 153729                   1
gq8AODNzgs 162941                   1
gqMnbaIXas 121306                   1
gpmTcmMa8i 164855                   1
goP9m92rOd 83326                    1
gly5DMhl9z 135935                   1
gmAcLEVgnb 165355                   1
gmOoX8uqMS 83013                    1
gmd3Igcb15 164855                   1
gn7aYYbeFM 81022                    1
gnHJEqWYN7 85405                    1
gnhZqTUsTs 120759                   1
go87U4zwZ0 83412                    1
goDxUJLXfG 131244                   1
goFf6cupZd 165742                   1
gqRtfMVBhB 121348                   1
ggXyLfxZjF 84811                    1
gdUpaAsoVB 93120                    1
gdcUr3lcBC 83535                    1
gdmp7epgto 84148                    1
gek0fOqlWM 93654                    1
gYyOttyok1 160404                   1
gZHMD6Znu0 84322                    1
gZVlop6MVv 133217                   1
ga5tPGpYIB 112122                   1
gaEbr602wn 164855                   1
...                               ...
WPn7uHspNJ 164855                  17
vdXqQtIrvU 164855                  17
UlfzIht3E8 165856                  17
UhjNSKaSyV 164855                  17
rLpRbtzBQJ 165409                  17
dozKCcqod9 164855                  18
IhH9v9ZfEw 164855                  18
MTmCNouHyV 165402                  18
17o1JduKkZ 165355                  18
upzhFvx7tO 164855                  18
skWykuirsV 164855                  19
9HmEnxus4G 124645                  19
hiqKaPZqjd 165856                  19
TjDfywjgtT 165856                  19
N5cfhuiNdn 164855                  20
qhH3hHcQtg 164855                  21
iedDbngsDd 164855                  22
kwtnzOgFZt 164855                  22
C7sttSHXLH 164855                  25
sVyncdp8fh 164855                  25
oUNAwY3E9i 165355                  25
sAThFLIoO9 164855                  27
SlYAiGeZdd 165856                  27
MfwejEEBAO 164855                  28
yhVEOllOhJ 164855                  28
ANhwHcIbQf 164855                  29
dogBjjxgvf 165358                  30
uxuRjaPxg6 165358                  31
Cpab8gNufn 164855                  31
jQxgCpmdAU 164855                  31
A5KwEE2uYl 165355                  33
wkB0rtda72 215852                  33
dACQWsIALT 113520                  36
ikS9wFcIt8 103229                  40
mp2XkQ7Lij 164855                  41
LyaMujNn6o 164855                  42
qP6ZSEhsSX 164855                  43
za5SuxpoJu 164855                  51
0flmswDsbu 164855                  55
tgsyTV3mAn 165358                  57
nl3obCpHit 164855                  64
nxQQYd0bD9 164855                  82
bYsVfeflI5 164855                  83
aSYAlmmLRm 164855                  91
amF73baqn6 165415                  98
dyiJoSCokG 165856                 111
kD2GbXVwHC 164855                 137
k18vohkJYi 164855                 144
tREXdlqVVc 164855                 198
Nk0dDMNlbK 164855                 452

[9590 rows x 1 columns]